name: Build, Test and Publish

on: [ pull_request , release ]

jobs:
  setup:
    name: Setup, Build, Publish
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
          id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42
          args: --timeout=10m
      - name: Build the docker-compose stack
        run: docker-compose up -d
      - name: wait for db-preparation
        run: sleep 10
      - name: Unit Tests
        run: go test -v ./...

      - name: Integration Tests
        run: go test -v ./integration -tags integration
      - name: clean-up
        run: docker-compose down
